/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PresentDeckIdRouteImport } from './routes/present.$deckId'
import { Route as DecksDeckIdRouteImport } from './routes/decks.$deckId'
import { Route as PresentDeckIdNotesRouteImport } from './routes/present.$deckId.notes'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentDeckIdRoute = PresentDeckIdRouteImport.update({
  id: '/present/$deckId',
  path: '/present/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdRoute = DecksDeckIdRouteImport.update({
  id: '/decks/$deckId',
  path: '/decks/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentDeckIdNotesRoute = PresentDeckIdNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => PresentDeckIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/present/$deckId': typeof PresentDeckIdRouteWithChildren
  '/present/$deckId/notes': typeof PresentDeckIdNotesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/present/$deckId': typeof PresentDeckIdRouteWithChildren
  '/present/$deckId/notes': typeof PresentDeckIdNotesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/present/$deckId': typeof PresentDeckIdRouteWithChildren
  '/present/$deckId/notes': typeof PresentDeckIdNotesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/decks/$deckId'
    | '/present/$deckId'
    | '/present/$deckId/notes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/decks/$deckId'
    | '/present/$deckId'
    | '/present/$deckId/notes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/decks/$deckId'
    | '/present/$deckId'
    | '/present/$deckId/notes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DecksDeckIdRoute: typeof DecksDeckIdRoute
  PresentDeckIdRoute: typeof PresentDeckIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present/$deckId': {
      id: '/present/$deckId'
      path: '/present/$deckId'
      fullPath: '/present/$deckId'
      preLoaderRoute: typeof PresentDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId': {
      id: '/decks/$deckId'
      path: '/decks/$deckId'
      fullPath: '/decks/$deckId'
      preLoaderRoute: typeof DecksDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present/$deckId/notes': {
      id: '/present/$deckId/notes'
      path: '/notes'
      fullPath: '/present/$deckId/notes'
      preLoaderRoute: typeof PresentDeckIdNotesRouteImport
      parentRoute: typeof PresentDeckIdRoute
    }
  }
}

interface PresentDeckIdRouteChildren {
  PresentDeckIdNotesRoute: typeof PresentDeckIdNotesRoute
}

const PresentDeckIdRouteChildren: PresentDeckIdRouteChildren = {
  PresentDeckIdNotesRoute: PresentDeckIdNotesRoute,
}

const PresentDeckIdRouteWithChildren = PresentDeckIdRoute._addFileChildren(
  PresentDeckIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DecksDeckIdRoute: DecksDeckIdRoute,
  PresentDeckIdRoute: PresentDeckIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
